version: "3.8"
services:
    # PHP Service
    php:
        container_name: php
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database

    # PHP Service
    # Database Server
    database:
        container_name: db
        image: mysql:5.7
        ports:
            -   3310:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        container_name: pma
        image: phpmyadmin/phpmyadmin
        links:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_USER: 'root'
            PMA_PASSWORD: 'S3mS2m@#'
            UPLOAD_LIMIT: 64M
        restart: always
        ports:
            - 8081:80
    # Queue Server
    # Node Server
    node:
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true

volumes:
    db-data: ~
