export const formToolbar = [{
    key: 'Header',
    name: 'Header Text',
    icon: 'fa fa-header',
    "static": true,
    content: 'Placeholder Text...',
    canHaveOptionValue: false,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,  
    canHaveDisplayHorizontal: false,
  }, {
    key: 'Dropdown',
    canHaveAnswer: true,
    name: 'Dropdown',
    icon: 'fa fa-caret-square-o-down',
    label: 'Placeholder Label',
    field_name: 'dropdown_',
    options: [],
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
    dirty: false
  }, {
    key: 'Tags',
    canHaveAnswer: true,
    name: 'Multi-select Dropdown',
    icon: 'fa fa-tags',
    label: 'Placeholder Label',
    field_name: 'tags_',
    options: [],
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
  }, {
    key: 'Checkboxes',
    canHaveAnswer: true,
    name: 'Checkboxes',
    icon: 'fa fa-check-square-o',
    label: 'Placeholder Label',
    field_name: 'checkboxes_',
    options: [],
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
  }, {
    key: 'RadioButtons',
    canHaveAnswer: true,
    name: 'Radio Buttons',
    icon: 'fa fa-dot-circle-o',
    label: 'Placeholder Label',
    field_name: 'radiobuttons_',
    options: [],
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
  }, {
    key: 'TextInput',
    canHaveAnswer: true,
    name: 'Text Input',
    label: 'Placeholder Label',
    icon: 'fa fa-font',
    field_name: 'text_input_',
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
  }, {
    key: 'NumberInput',
    canHaveAnswer: true,
    name: 'Number Input',
    label: 'Placeholder Label',
    icon: 'fa fa-plus',
    field_name: 'number_input_',
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
  }, {
    key: 'TextArea',
    canHaveAnswer: true,
    name: 'Multi-line Input',
    label: 'Placeholder Label',
    icon: 'fa fa-text-height',
    field_name: 'text_area_',
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
  }, {
    key: 'DatePicker',
    canDefaultToday: true,
    canReadOnly: true,
    dateFormat: 'MM/dd/yyyy',
    timeFormat: 'hh:mm aa',
    showTimeSelect: false,
    showTimeSelectOnly: false,
    name: 'Date',
    icon: 'fa fa-calendar',
    label: 'Placeholder Label',
    field_name: 'date_picker_',
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
  }, {
    key: 'Camera',
    name: 'Camera',
    icon: 'fa fa-camera',
    label: 'Placeholder Label',
    field_name: 'camera_',
    canHaveOptionValue: true,
    canHaveAlternateForm: false,
    canHaveOptionCorrect: false,
    canHavePageBreakBefore: false,
    canHaveDisplayHorizontal: false,
  }]